// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGfcZxnnwJq-TjA9jS8m-n9JcWr5JntIg',
    appId: '1:601988865276:web:135ae4ebbd76acc315cb79',
    messagingSenderId: '601988865276',
    projectId: 'safar-ticketing',
    authDomain: 'safar-ticketing.firebaseapp.com',
    storageBucket: 'safar-ticketing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoiS2agHE1Gy8NVFcsjxAO5BhJPjPqkwM',
    appId: '1:601988865276:android:de0232646f987c2315cb79',
    messagingSenderId: '601988865276',
    projectId: 'safar-ticketing',
    storageBucket: 'safar-ticketing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_A--Erh2FdVHw86Q7vzyQJtHdnuTjk4',
    appId: '1:601988865276:ios:a4cee01736a7ba1615cb79',
    messagingSenderId: '601988865276',
    projectId: 'safar-ticketing',
    storageBucket: 'safar-ticketing.appspot.com',
    iosBundleId: 'com.safar.safar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_A--Erh2FdVHw86Q7vzyQJtHdnuTjk4',
    appId: '1:601988865276:ios:a4cee01736a7ba1615cb79',
    messagingSenderId: '601988865276',
    projectId: 'safar-ticketing',
    storageBucket: 'safar-ticketing.appspot.com',
    iosBundleId: 'com.safar.safar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGfcZxnnwJq-TjA9jS8m-n9JcWr5JntIg',
    appId: '1:601988865276:web:1960fc11d6f24e3115cb79',
    messagingSenderId: '601988865276',
    projectId: 'safar-ticketing',
    authDomain: 'safar-ticketing.firebaseapp.com',
    storageBucket: 'safar-ticketing.appspot.com',
  );
}
